services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 --timeout 1800 --workers 4 run:app
    volumes:
      - ./uploads:/app/uploads
      - ./config.json:/app/config.json
      - db_data:/app/database
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    depends_on:
      - redis

  worker:
    build: .
    command: ["celery", "-A", "run.celery", "worker", "--loglevel=info", "--concurrency=4"]
    volumes:
      - ./uploads:/app/uploads
      - ./config.json:/app/config.json
      - db_data:/app/database
    env_file:
      - .env
    environment:
      - ROLE=background
    depends_on:
      - redis

  beat:
    build: .
    command: ["celery", "-A", "run.celery", "beat", "--loglevel=info"]
    volumes:
      - ./config.json:/app/config.json
      - db_data:/app/database
    env_file:
      - .env
    environment:
      - ROLE=background
    depends_on:
      - redis

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"

volumes:
  db_data: